name: Automação de deploy

on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '0 10 15 * *'


jobs:
  Shinyapps:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v6

      - name: Publicar dashboard
        run: |
          pip install rsconnect-python
          rsconnect add --account ${{ secrets.ACCOUNT }} --name ${{ secrets.NAME }} --token ${{ secrets.TOKEN }} --secret ${{ secrets.SECRET }}
          rsconnect deploy shiny . --title previsa_ipca

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Deploy automático
